target ‘Yoga’ do
platform :ios ,'8.0'
pod 'AFNetworking' , '~>3.1.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'MJRefresh', '~> 3.1.12'
pod 'GTMBase64', '~> 1.0.0'
pod 'GTSDK'
pod 'Heap'
pod 'Firebase/Core'
pod 'Firebase/Crash'
pod 'Firebase/Performance'
pod 'FBNotifications'
pod 'BuglyHotfix'
pod 'MJExtension', '~> 3.0.13'
end
